---
## 🎁 가산점

### A. 데이터의 다양성
- NTP ICE 내 다양한 데이터셋 모두 활용 가능. (https://ice.ntp.niehs.nih.gov/DATASETDESCRIPTION)
### B. Feature(descriptor)의 다양성
- rdkit, VEGA, 등
### 💬 추가 설명 (자유 기술)

# 기말고사 Template 1 — Data Pipeline

**이름:** __장다예__ &nbsp; **학번:** ____20251281____ &nbsp;

---

## 📋 채점 기준 (총 50점)

| 항목 | 배점 | 채점 포인트 |
|---|---|---|
| **1. 데이터 분포 파악 및 전처리** | 15점 | 모델 개발 전, 중복 화합물 체크, smiles 코드 정리 등 모델 개발 전 확인해야 할 사항들을 확인. |
| **2. Descriptor 계산** | 15점 | 모델 개발에 사용할 descriptor의 다양성 |
| **3. 데이터 시각화 자료** | 15점 | 구조 분포, 라벨 비율 등 데이터 현황을 시각화한 자료 |
| **4. 코드 가독성 & 주석** | 5점 | 변수의 의미와 코드의 간결성을 평가. |

#### A. 데이터 소스의 다양성
- NTP ICE에서 구할 수 있는 다양한 데이터
- NTP ICE 외 추가 데이터 확보

## 📁 입력 / 출력 예시
- **입력**: `skin_irritation.xlsx` (NTP ICE) + (선택) 외부 데이터
- **출력**: `final_dataset_descriptors.csv`  (Chemical_Name, SMILES, label, 2D descriptor [+ fingerprint 등])

In [4]:
import pandas as pd

xls = pd.ExcelFile('endocrine.xlsx')
df = pd.read_excel('endocrine.xlsx', sheet_name=2)
df

,Record_ID,Data_Type,Chemical_Name,CASRN,DTXSID,Mixture,Species,Reported_Strain,Strain,Sex,...,Additional_Information,Endpoint,Response,Response_Unit,Reference,SMILES,Preferred_Name,Synonyms,URL_CompTox,URL_CEBS
0,endocrine_invivo_1,In Vivo,Bis(2-ethylhexyl)hexanedioate,103-23-1,DTXSID0020606,Chemical,Rat,NaN,NaN,Female,...,NaN,Call,Inactive,Unitless,Takeyoshi 2006; Not available; https://www.oec...,CCCCC(CC)COC(=O)CCCCC(=O)OCC(CC)CCCC,Bis(2-ethylhexyl)hexanedioate,103-23-1|Bis(2-ethylhexyl)hexanedioate|Adimoll...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID0020606
1,endocrine_invivo_2,In Vivo,Tamoxifen,10540-29-1,DTXSID1034187,Chemical,Rat,Holtzman,Holtzman,Female,...,NaN,Call,Active,Unitless,Jones et al. 1984; 6431104; 10.1021/jm00374a02...,CCC(=C(/C1=CC=CC=C1)C1=CC=C(OCCN(C)C)C=C1)C1=C...,Tamoxifen,"10540-29-1|Tamoxifen|(Z)-2-(4-(1,2-Diphenyl-1-...",https://comptox.epa.gov/dashboard/chemical/det...,NaN
2,endocrine_invivo_3,In Vivo,Tamoxifen,10540-29-1,DTXSID1034187,Chemical,Rat,Alderly,Alderley Park,Female,...,NaN,Call,Active,Unitless,Allen et al. 1980; 7470748; 10.1111/j.1476-538...,CCC(=C(/C1=CC=CC=C1)C1=CC=C(OCCN(C)C)C=C1)C1=C...,Tamoxifen,"10540-29-1|Tamoxifen|(Z)-2-(4-(1,2-Diphenyl-1-...",https://comptox.epa.gov/dashboard/chemical/det...,NaN
3,endocrine_invivo_4,In Vivo,Bis(2-ethylhexyl)hexanedioate,103-23-1,DTXSID0020606,Chemical,Rat,Crj:CD(SD)IGS,Sprague-Dawley,Female,...,NaN,Call,Inactive,Unitless,Akahori et al. 2008; 17904329; 10.1016/j.tiv.2...,CCCCC(CC)COC(=O)CCCCC(=O)OCC(CC)CCCC,Bis(2-ethylhexyl)hexanedioate,103-23-1|Bis(2-ethylhexyl)hexanedioate|Adimoll...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID0020606
4,endocrine_invivo_5,In Vivo,Tamoxifen,10540-29-1,DTXSID1034187,Chemical,Rat,NaN,NaN,Female,...,NaN,Call,Active,Unitless,Eppenberger et al. 1991; 1962598; 10.1097/0000...,CCC(=C(/C1=CC=CC=C1)C1=CC=C(OCCN(C)C)C=C1)C1=C...,Tamoxifen,"10540-29-1|Tamoxifen|(Z)-2-(4-(1,2-Diphenyl-1-...",https://comptox.epa.gov/dashboard/chemical/det...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2265,endocrine_invivo_238,In Vivo,17alpha-Ethinylestradiol,57-63-6,DTXSID5020576,Chemical,Rat,Wistar (Hsd/Cpb:WU),Wistar,Female,...,NaN,LOEL,1E-3,mg/kg/day,Freyberger et al. 2001; 11218048; 10.1007/s002...,[H][C@@]12CC[C@@](O)(C#C)[C@@]1(C)CC[C@]1([H])...,17alpha-Ethinylestradiol,57-63-6|17alpha-Ethinylestradiol|(17-alpha)-19...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID5020576
2266,endocrine_invivo_240,In Vivo,17alpha-Ethinylestradiol,57-63-6,DTXSID5020576,Chemical,Rat,Wistar Rj WI (SpF) Han,Wistar,Female,...,"Laboratory 4, Protocol A",LOEL,1E-3,mg/kg/day,Kanno et al. 2001; 11564613; 10.1289/ehp.01109...,[H][C@@]12CC[C@@](O)(C#C)[C@@]1(C)CC[C@]1([H])...,17alpha-Ethinylestradiol,57-63-6|17alpha-Ethinylestradiol|(17-alpha)-19...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID5020576
2267,endocrine_invivo_957,In Vivo,17alpha-Ethinylestradiol,57-63-6,DTXSID5020576,Chemical,Rat,SD Crl CD(SD) IGS BR,Sprague-Dawley,Female,...,"Laboratory 12, Protocol B",LOEL,3e-04,mg/kg/day,Kleinstreuer et al. 2016; 26431337; 10.1289/eh...,[H][C@@]12CC[C@@](O)(C#C)[C@@]1(C)CC[C@]1([H])...,17alpha-Ethinylestradiol,57-63-6|17alpha-Ethinylestradiol|(17-alpha)-19...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID5020576
2268,endocrine_invivo_451,In Vivo,Methoxychlor,72-43-5,DTXSID9020827,Chemical,Rat,SD IC:OFA SD (IOPS Caw),Sprague-Dawley,Female,...,Protocol B,Call,Active,Unitless,Kanno et al. 2003; 12948896; 10.1289/ehp.5780|...,COC1=CC=C(C=C1)C(C1=CC=C(OC)C=C1)C(Cl)(Cl)Cl,Methoxychlor,"72-43-5|Methoxychlor|1,1-(2,2,2-Trichloroethyl...",https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID9020827
2269,endocrine_invivo_245,In Vivo,17alpha-Ethinylestradiol,57-63-6,DTXSID5020576,Chemical,Rat,Wistar (mol:Wistar/Han),Wistar,Female,...,"Laboratory 17, Protocol B",LOEL,3e-04,mg/kg/day,Kleinstreuer et al. 2016; 26431337; 10.1289/eh...,[H][C@@]12CC[C@@](O)(C#C)[C@@]1(C)CC[C@]1([H])...,17alpha-Ethinylestradiol,57-63-6|17alpha-Ethinylestradiol|(17-alpha)-19...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID5020576

In [8]:
df['Species'].value_counts()

df_rat = df[df['Species']=='Rat']
df_rat

,Record_ID,Data_Type,Chemical_Name,CASRN,DTXSID,Mixture,Species,Reported_Strain,Strain,Sex,...,Additional_Information,Endpoint,Response,Response_Unit,Reference,SMILES,Preferred_Name,Synonyms,URL_CompTox,URL_CEBS
0,endocrine_invivo_1,In Vivo,Bis(2-ethylhexyl)hexanedioate,103-23-1,DTXSID0020606,Chemical,Rat,NaN,NaN,Female,...,NaN,Call,Inactive,Unitless,Takeyoshi 2006; Not available; https://www.oec...,CCCCC(CC)COC(=O)CCCCC(=O)OCC(CC)CCCC,Bis(2-ethylhexyl)hexanedioate,103-23-1|Bis(2-ethylhexyl)hexanedioate|Adimoll...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID0020606
1,endocrine_invivo_2,In Vivo,Tamoxifen,10540-29-1,DTXSID1034187,Chemical,Rat,Holtzman,Holtzman,Female,...,NaN,Call,Active,Unitless,Jones et al. 1984; 6431104; 10.1021/jm00374a02...,CCC(=C(/C1=CC=CC=C1)C1=CC=C(OCCN(C)C)C=C1)C1=C...,Tamoxifen,"10540-29-1|Tamoxifen|(Z)-2-(4-(1,2-Diphenyl-1-...",https://comptox.epa.gov/dashboard/chemical/det...,NaN
2,endocrine_invivo_3,In Vivo,Tamoxifen,10540-29-1,DTXSID1034187,Chemical,Rat,Alderly,Alderley Park,Female,...,NaN,Call,Active,Unitless,Allen et al. 1980; 7470748; 10.1111/j.1476-538...,CCC(=C(/C1=CC=CC=C1)C1=CC=C(OCCN(C)C)C=C1)C1=C...,Tamoxifen,"10540-29-1|Tamoxifen|(Z)-2-(4-(1,2-Diphenyl-1-...",https://comptox.epa.gov/dashboard/chemical/det...,NaN
3,endocrine_invivo_4,In Vivo,Bis(2-ethylhexyl)hexanedioate,103-23-1,DTXSID0020606,Chemical,Rat,Crj:CD(SD)IGS,Sprague-Dawley,Female,...,NaN,Call,Inactive,Unitless,Akahori et al. 2008; 17904329; 10.1016/j.tiv.2...,CCCCC(CC)COC(=O)CCCCC(=O)OCC(CC)CCCC,Bis(2-ethylhexyl)hexanedioate,103-23-1|Bis(2-ethylhexyl)hexanedioate|Adimoll...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID0020606
4,endocrine_invivo_5,In Vivo,Tamoxifen,10540-29-1,DTXSID1034187,Chemical,Rat,NaN,NaN,Female,...,NaN,Call,Active,Unitless,Eppenberger et al. 1991; 1962598; 10.1097/0000...,CCC(=C(/C1=CC=CC=C1)C1=CC=C(OCCN(C)C)C=C1)C1=C...,Tamoxifen,"10540-29-1|Tamoxifen|(Z)-2-(4-(1,2-Diphenyl-1-...",https://comptox.epa.gov/dashboard/chemical/det...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2265,endocrine_invivo_238,In Vivo,17alpha-Ethinylestradiol,57-63-6,DTXSID5020576,Chemical,Rat,Wistar (Hsd/Cpb:WU),Wistar,Female,...,NaN,LOEL,1E-3,mg/kg/day,Freyberger et al. 2001; 11218048; 10.1007/s002...,[H][C@@]12CC[C@@](O)(C#C)[C@@]1(C)CC[C@]1([H])...,17alpha-Ethinylestradiol,57-63-6|17alpha-Ethinylestradiol|(17-alpha)-19...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID5020576
2266,endocrine_invivo_240,In Vivo,17alpha-Ethinylestradiol,57-63-6,DTXSID5020576,Chemical,Rat,Wistar Rj WI (SpF) Han,Wistar,Female,...,"Laboratory 4, Protocol A",LOEL,1E-3,mg/kg/day,Kanno et al. 2001; 11564613; 10.1289/ehp.01109...,[H][C@@]12CC[C@@](O)(C#C)[C@@]1(C)CC[C@]1([H])...,17alpha-Ethinylestradiol,57-63-6|17alpha-Ethinylestradiol|(17-alpha)-19...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID5020576
2267,endocrine_invivo_957,In Vivo,17alpha-Ethinylestradiol,57-63-6,DTXSID5020576,Chemical,Rat,SD Crl CD(SD) IGS BR,Sprague-Dawley,Female,...,"Laboratory 12, Protocol B",LOEL,3e-04,mg/kg/day,Kleinstreuer et al. 2016; 26431337; 10.1289/eh...,[H][C@@]12CC[C@@](O)(C#C)[C@@]1(C)CC[C@]1([H])...,17alpha-Ethinylestradiol,57-63-6|17alpha-Ethinylestradiol|(17-alpha)-19...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID5020576
2268,endocrine_invivo_451,In Vivo,Methoxychlor,72-43-5,DTXSID9020827,Chemical,Rat,SD IC:OFA SD (IOPS Caw),Sprague-Dawley,Female,...,Protocol B,Call,Active,Unitless,Kanno et al. 2003; 12948896; 10.1289/ehp.5780|...,COC1=CC=C(C=C1)C(C1=CC=C(OC)C=C1)C(Cl)(Cl)Cl,Methoxychlor,"72-43-5|Methoxychlor|1,1-(2,2,2-Trichloroethyl...",https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID9020827
2269,endocrine_invivo_245,In Vivo,17alpha-Ethinylestradiol,57-63-6,DTXSID5020576,Chemical,Rat,Wistar (mol:Wistar/Han),Wistar,Female,...,"Laboratory 17, Protocol B",LOEL,3e-04,mg/kg/day,Kleinstreuer et al. 2016; 26431337; 10.1289/eh...,[H][C@@]12CC[C@@](O)(C#C)[C@@]1(C)CC[C@]1([H])...,17alpha-Ethinylestradiol,57-63-6|17alpha-Ethinylestradiol|(17-alpha)-19...,https://comptox.epa.gov/dashboard/chemical/det...,https://doi.org/10.22427/NTP-DATA-DTXSID5020576

In [9]:
df_rat['Endpoint'].value_counts()

Endpoint
Call                                  909
LOEL                                  623
NOEL                                  351
Uterine weight increase vs control    304
Relative potency                       10
Name: count, dtype: int64